# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 8888
  config.vm.hostname = "vm1"
  config.vm.define "vm1"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2024"
  config.vm.provision "shell", inline: <<-SHELL
    yum install -y epel-release
    yum install -y nginx
    echo "<h2>Webserver with Nginx</h2><br>Build by Vagrant" > /usr/share/nginx/html/index.html
    systemctl start nginx
     systemctl enable nginx
    
     SHELL

end
end