# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
  vm1.vm.box = "centos/7"
  vm1.vm.box_check_update = false
  vm1.vm.network "forwarded_port", guest: 80, host: 8888
  vm1.vm.hostname = "vm1"
  vm1.vm.define "vm1"
  vm1.vm.provider "virtualbox" do |vb|
    vb.memory = "2024"
  end
  vm1.vm.provision "shell", inline: <<-SHELL
    yum install -y epel-release
    yum install -y nginx
    echo "<h2>Webserver with Nginx</h2><br>Build by Vagrant" > /usr/share/nginx/html/index.html
    systemctl start nginx
     systemctl enable nginx
    
     SHELL
end

config.vm.define "vm2" do |vm2|
  vm2.vm.box = "ubuntu/focal64"
  vm2.vm.box_check_update = false
  vm2.vm.network "forwarded_port", guest: 80, host: 8881
  vm2.vm.hostname = "vm2"
  vm2.vm.define "vm2"
  vm2.vm.provider "virtualbox" do |vb2|
    vb2.memory = "2024"
  end
  vm2.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y nginx
  echo "<h2>Webserver with Nginx</h2><br>Build by Vagrant" > /var/www/html/index.nginx-debian.html
    systemctl start nginx
     systemctl enable nginx
     SHELL
  end
end